vich_uploader:
    db_driver: orm

    mappings:
        politician_images:
            uri_prefix: '%app.path.politician_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.politician_images%'
